name: Setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: ./pnpm-lock.yaml
        node-version-file: './package.json'
    - run: pnpm install
      shell: bash
